name: pay_web
description: A plug-in to add support for payments on the web side of Flutter applications.
version: 1.0.0
homepage: https://github.com/google-pay/flutter-plugin
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  assets:
    - assets/images/
    
  plugin:
    implements: pay
    platforms:
      web:
        pluginClass: PayWebPlugin
        fileName: pay_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pay_platform_interface:
    path: ../pay_platform_interface
  web: ">=0.5.1 <2.0.0"
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  flutter_lints: ^5.0.0
